# name: Test

# on: [push]

# jobs:
#   test:
#     name: Run test
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/setup-python@v5
#         with:
#           python-version: "3.10"
#           architecture: "x64"
#       - name: Install Dependencies
#         run: |
#           python3 -m venv venv
#           . venv/bin/activate
#           pip install pip
#           pip install poetry
#           poetry install
